### ISSUE TITLE
Full HP/EP restore bonus from collecting all items in map doesn't fully recover HP

### ISSUE THREAD

**Issue by KuromeKT** [Sumwunn/DoomRPG#39]
For some reason, the "full HP/EP restore" bonus that comes with collecting all items present in the map (and the same bonus that comes with 100%'ing all monsters, items & secrets) doesn't affect your HP at all. The EP restore still works though.

**Comment by KuromeKT** [comment]
Most likely an extension of this bug, but HP regeneration is also not working.

**Comment by Demiosis** [comment]
Are you SURE you weren't buffed by a Soul sphere but gotten damaged but not enough so your regular hp was already covered? Once again this never happened to me with all the gameplay I did!

**Comment by KuromeKT** [comment]
Yes. It's plain to see given how my mugshot would remain wounded before and after, which proves there were no changes to my HP.

**Comment by Demiosis** [comment]
Seem like you're using a wrong version of Gzdoom or using the launcher (never had much sucess running the mod properly with it if I really wanna be honest with you... ^^')' or something similar , make sure you have latest Gzdoom files , latest doomrpg files + other mods like Drla and finally run your file list in a .bat file. 

Example of a .Bat file:

"GZDOOM.exe" -file "mappackname.wad"  "DoomRL_Arsenal_1.1.1.pk3" "DoomRL_Monsters_Beta_7.1.pk3" "doomrl_arsenal_hud_1.05.wad" "DoomRPG.zip" "DoomRPG-RLArsenal.zip" "DoomRPG-RLMonsters.zip" "Doomrpg-BrightMaps.zip"

Also, its compatible with this mod list :

DoomRL Arsenal - [1.1.1] [MP-B7.1].
LegenDoom v2.5.
Colourful Hell v0.97b.
Custom version of Jimmy's Jukebox Instant Randomizer has been included which allows DRPG's map events and Outpost music to play.

BUT, do not put more than one at a time or else it WILL explode and burn ^^'

**Comment by Zapoopa** [comment]
Tested at 3.7.1, 4.0.0. 4.1.1... any lower version crushes by "version expected" error, Anyway, healing system is broken. Restore bonus, regeneration and medkits not working. If problem with version, so say what exactly version needed? 

Btw, new version DoomRl does not include hud wad.

**Comment by Demiosis** [comment]
Like KuromeKT you skipped a important part of my wall of text mr Zapoopa. The problem is most likely related to the drpg launcher. REFRAIN FROM USING IT! use a .bat file instead. Btw DoomRL old hud still work perfectly and I prefer that one to the new one and I use Gzdoom 3.7.2. . 

Bullet popoffs , hp/ep regen, and xp on nightmare soul,hell mine , de-vile (except the souls ones spawned/rezzed from pain elemental, arch viles since THESE aren't supposed to give any like fallen ones in diablo 2 , you cant kill them all over again for free shit) 

All 3 of these reported bugs work on my side with the latest version of both drpg and drla. (which I run using a .bat file NOT the laucher)

**Comment by KuromeKT** [comment]
I've never used the DRPG launcher, as I've always ran the mod via ZDoom Launcher instead. The order of wads is the same as yours, except no HUD wad and Brightmaps comes before the DRPG DRLA wads (and Brightmaps in itself is an inconsequential wad and its placing in the order shouldn't matter).

The Nightmare Soul/Hellmine bug has been there for a long time, I just didn't think of that as a bug at the time, until I realised regular Lost Souls and The Hungry do give XP just fine, which did not make for consistent behaviour. The De-Vile bug happens because the De-Vile wasn't properly implemented into DRPG (which makes sense, he's a new monster that came with DRLA 1.1 and DRPG didn't support that until just now).

**Comment by Demiosis** [comment]
Thats exactly why it does not work, you really REALLY need a .bat to run this mod

**Comment by FoxMcloud5655** [comment]
My brother and I both have this same issue.  We are running the exact same PWADs as you've listed in the same order.  I use the ZDoom Launcher and my brother uses a .bat file I created for him, and we still have this issue.

At first, I thought that HP Regen was disabled due to it being OP when DRLA was present, but after seeing this potential bug, I'm not so sure.

**Comment by FoxMcloud5655** [comment]
Just tested (with a .bat file) DoomRPG just by itself; I am having this issue currently.  This is happening even when compiled with the version present on GitHub from the source.

I'll see what I can do to fix this, if it's something I can fix.

**Comment by FoxMcloud5655** [comment]
I've fixed this bug.  HealThing no longer works for some reason, so I replaced each instance of it with a custom script called HealPlayer.  If you'd like this fix, I can make a PR.

**Comment by Demiosis** [comment]
Im using the master branch btw , most likely the reason why everything work perfectly on my side and not yours folk.. the master build must be more updated than the release build.

**Comment by FoxMcloud5655** [comment]
Maybe, but everything on my end is compiled using the master branch as well.

It looks like my "fix" may be unsafe; I think it's causing multiplayer games to go out of sync.  I'll have to look into it more.  Also, if you'd like a copy of my entire setup (minus doom2.wad, obviously), I can zip it up so you can compare.

**Comment by Demiosis** [comment]
Really dunno what to tell you... Here's shots from the latest build showing what im currently seeing:
![Screenshot_Doom_20190511_130338](https://user-images.githubusercontent.com/5500931/57572814-e2248b80-73ed-11e9-8783-fb895d07b680.png)
![Screenshot_Doom_20190511_130342](https://user-images.githubusercontent.com/5500931/57572815-e2248b80-73ed-11e9-8e58-737d429a338a.png)
![Screenshot_Doom_20190511_130419](https://user-images.githubusercontent.com/5500931/57572816-e2248b80-73ed-11e9-89cb-bf236887a43c.png)
![Screenshot_Doom_20190511_130429](https://user-images.githubusercontent.com/5500931/57572817-e2bd2200-73ed-11e9-9c2f-0b11332b7b48.png)
![Screenshot_Doom_20190511_130527](https://user-images.githubusercontent.com/5500931/57572818-e2bd2200-73ed-11e9-8318-4e98604664d4.png)
![Screenshot_Doom_20190511_130531](https://user-images.githubusercontent.com/5500931/57572819-e2bd2200-73ed-11e9-93e5-51933e0ca770.png)

And by the way , the no xp on kill for nightmare soul is actually true , forced a nightmare difficulty with  a lost soul only oblige maps. could not get a smidge of Xp.

**Comment by Zapoopa** [comment]
Emmm,, i never use launcher... only bat. files, and order of files 100% same as yours (except Hud wad). Tested at 3.7.2 modern and vintage for 64x and 32x, with last master branch DoomRPG and redownloaded DoomRL and DoomRl monsterpack. Restore bonus and regeneretion still not works. 

Btw, in the last experemental version (15 mar, thats actually older then master brach), everything looks normal. 

Demiosis, could you say me date of yours DoomRPG build? I mean MM-DD-YEAR

**Comment by FoxMcloud5655** [comment]
@Demiosis Since your build and configuration seem to be working, do you mind attaching everything needed to replicate your setup (minus doom2.wad, of course)?

In case if someone wants to replace their ACS library inside of DoomRPG, I'm attaching it to this post.
[DoomRPG.zip](https://github.com/Sumwunn/DoomRPG/files/3170147/DoomRPG.zip)

**Comment by Sumwunn** [comment]
Hey guys! I've returned, for now.. :)
Wow all these new issues, lots of fixing to do!

Anyway:
So when I changed how PlayerDamage was handled it broke HealThing (hmm) for healing the player. So I swapped HealThing for DRPGs own healing functions.

Please test out experimental for me, thanks!

**Comment by Zapoopa** [comment]
Well, seems all right. Testet at 4.1.1. modern 64x. Need to play a little bit more (i mean i want to check random script crush).

**Comment by FoxMcloud5655** [comment]
You got it.  I'll test the experimental branch as soon as I get home and on my computer, then report back!  I'll be giving it a test in multiplayer as well to see how stable it is.

**Comment by FoxMcloud5655** [comment]
Alright; after heavy testing in multiplayer, it does work and is more stable than my own fix.  However, it still causes players to go out of sync, though not as often.  It's workable, as long as you're willing to save your character/create a save file after every map so you don't lose too much progress.

**Comment by Sumwunn** [comment]
I've fixed DRPG player health not staying in sync with HealThing() and reinstated those calls to it.

Please test again, thank you! 👍

**Comment by FoxMcloud5655** [comment]
As for the syncing of player health, it is perfect now.  Thanks!

We still have desync issues when entering the map "Tricks and Traps" on the original DOOM2.WAD with Armageddon difficulty and DRLA monsters, but I suspect that it has something to do with the Cacabuses, not with player HP.

**Comment by Sumwunn** [comment]
Ok I merged the changes into master.

Hmm, have you tried playing w/ LegenDoom or just Extras?

**Comment by FoxMcloud5655** [comment]
No, but I have definitely narrowed it down to Cacobyss's; even without DoomRPG enabled, they still make us go out of sync.

**Comment by Sumwunn** [comment]
Hahaha so it's not DRPG for once! Good to know. :D

I'd post that in DRLA's thread, unless someone already reported it or something similar.

**Comment by FoxMcloud5655** [comment]
More people talking about the issue is totally fine with me!
